### ISSUE TITLE
Plugin ignores font assets

### ISSUE THREAD

**Issue by ElijahSink** [laynezh/vite-plugin-lib-assets#22]
Fantastic plugin! This is helping me reduce my bundle size tremendously. However, I'm having an issue with fonts:

Given an imported `.scss` file with the contents:
```scss
@font-face {
  font-family: 'VectoraLTStd';
  src: url('@Assets/fonts/interface/VectoraLTStd-Roman.woff2') format('woff2'), url('@Assets/fonts/interface/VectoraLTStd-Roman.woff') format('woff');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'VectoraLTStd';
  src: url('@Assets/fonts/interface/VectoraLTStd-Bold.woff2') format('woff2'), url('@Assets/fonts/interface/VectoraLTStd-Bold.woff') format('woff');
  font-weight: bold;
  font-style: normal;
}
```

They continue to be inlined in the generated CSS file in base64 as opposed to being copied as static assets and referenced by URL.

Here's my plugin config:
```ts
libAssetsPlugin({
  exclude: /.*\.(svg)/,
  limit: 1024 * 8,
  name: "[name].[hash:8].[ext]"
}),
```

I've checked that the default `include` setting includes `.woff` and `.woff2`, so I'm not sure why these aren't getting picked up.
