### ISSUE TITLE
Mime type resolution on unknown type

### ISSUE THREAD

**Issue by deather** [laynezh/vite-plugin-lib-assets#76]
Hello,

I encountered a problem using the plugin. I have a less file that looks like this.

```less
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url('fonts/glyphicons-halflings-regular.eot') format('embedded-opentype'),;
}
```

The problem is that the mrmime library cannot resolve this mime type. In this case the plugin automatically set the mimetype to **application/octet-stream** [here](https://github.com/laynezh/vite-plugin-lib-assets/blob/d73e77e5e1f99c6d580421bab9bdbd67fe496b17/src/utils.ts#L59), but in the generated css file it's specified as **application/vnd.ms-fontobject**. So the [line](https://github.com/laynezh/vite-plugin-lib-assets/blob/d73e77e5e1f99c6d580421bab9bdbd67fe496b17/src/index.ts#L161) can't replace the font.

So there are 2 problems:

1. Why can't the mrmime library resolve the mimetype of .eot files ? (I open an [issue](https://github.com/lukeed/mrmime/issues/9))
2. Shouldn't mime types that haven't been resolved be handled differently from others ?

These is the CSS generated from the less above :

```
@font-face {
  font-family: Glyphicons Halflings;
  src: url(data:application/vnd.ms-fontobject;base64,...) format('embedded-opentype');
}
```

I hope you can understood me. Thank you for your plugin and reading.
