### ISSUE TITLE
Add vite as peerDependency

### ISSUE THREAD

**Issue by vahnag** [laynezh/vite-plugin-lib-assets#84]
Some package managers require correct peerDependency configuration to appropriately hoist packages in a monorepo.

Because peerDependency is not set in package json I'm currently having to work around it by manually specifying it in the `.yarnrc.yml` file as so:

```yaml
packageExtensions:
  "@laynezh/vite-plugin-lib-assets@*":
    peerDependencies:
      vite: "*"

```

Here's an [example](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/package.json#L47-L49) with correct configuration.
